# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Config_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore,  QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(529, 399)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(30, 50, 191, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(250, 50, 91, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(390, 50, 101, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(30, 120, 241, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(390, 120, 101, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(30, 200, 101, 21))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(390, 240, 101, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(390, 180, 101, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.Config_Button = QtWidgets.QPushButton(Dialog)
        self.Config_Button.setGeometry(QtCore.QRect(210, 280, 111, 31))
        self.Config_Button.setObjectName("Config_Button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(250, 20, 91, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(390, 10, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 30, 91, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(100, 80, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(90, 100, 131, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(390, 90, 101, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 170, 111, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(390, 210, 111, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(390, 150, 121, 21))
        self.label_10.setObjectName("label_10")
        self.Config_number_line = QtWidgets.QLineEdit(Dialog)
        self.Config_number_line.setGeometry(QtCore.QRect(160, 330, 291, 20))
        self.Config_number_line.setText("")
        self.Config_number_line.setObjectName("Config_number_line")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 330, 121, 21))
        self.label_11.setObjectName("label_11")
        self.Freq_line = QtWidgets.QLineEdit(Dialog)
        self.Freq_line.setGeometry(QtCore.QRect(170, 200, 51, 20))
        self.Freq_line.setObjectName("Freq_line")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(160, 170, 91, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(230, 200, 31, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(160, 360, 291, 21))
        self.label_14.setObjectName("label_14")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Конфигуратор КЕДР-2.0 (Демонстрационная версия)"))
        self.comboBox.setItemText(0, _translate("Dialog", "ВЧ"))
        self.comboBox.setItemText(1, _translate("Dialog", "ВОЛС"))
        self.comboBox.setItemText(2, _translate("Dialog", "МУЛЬТИПЛЕКСОР"))
        self.comboBox.setItemText(3, _translate("Dialog", "ВЧ-ВОЛС"))
        self.comboBox.setItemText(4, _translate("Dialog", "ВЧ-МУЛЬТИПЛЕКСОР"))
        self.comboBox.setItemText(5, _translate("Dialog", "ВОЛС-МУЛЬТИПЛЕКСОР"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "ПРМ"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "ПРД"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "ПРМ/ПРД"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "ПРМ32Ф"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "ПРМ16В"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "ПРМ32Ф"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "ПРД16В"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "ПРМ64Ф"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "ПРМ32В"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "ПРД64Ф"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "ПРД32В"))
        self.comboBox_3.setItemText(8, _translate("Dialog", "ПРМ32Ф/ПРД32Ф"))
        self.comboBox_3.setItemText(9, _translate("Dialog", "ПРМ32В/ПРМ32В"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "100BASETX(\"ЦКК1\")"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "100BASEFX(\"ЦКК2\")"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "RS-485(\"ЦКК1\")"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "100BASETX(\"ЦКК1\")/100BASEFX(\"ЦКК1\")"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "100BASETX(\"ЦКК1\")/100BASETX(\"ЦКК1\")"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "100BASEFX(\"ЦКК1\")/100BASETX(\"ЦКК2\")"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "IP20"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "IP21"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "ЛФ1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "ЛФ2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "ЛФ3"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "ЛФ4"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "ЛФ5"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "ЛФ6"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "без ТМ"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "с ТМ"))
        self.comboBox_8.setItemText(0, _translate("Dialog", "Медь"))
        self.comboBox_8.setItemText(1, _translate("Dialog", "Оптика"))
        self.Config_Button.setText(_translate("Dialog", "Конфигурировать"))
        self.label.setText(_translate("Dialog", "Тип канала (КК)"))
        self.label_2.setText(_translate("Dialog", "Направление(НН)"))
        self.label_3.setText(_translate("Dialog", "Тип дискретного"))
        self.label_4.setText(_translate("Dialog", "интерфейса (ДД)"))
        self.label_5.setText(_translate("Dialog", "Тип физического"))
        self.label_6.setText(_translate("Dialog", "подключения к ЛВС (СС)"))
        self.label_7.setText(_translate("Dialog", "Класс защиты (СС)"))
        self.label_8.setText(_translate("Dialog", "Исполнение ЛФ (ЛЛ)"))
        self.label_9.setText(_translate("Dialog", "Исполнение СФС (ТТ)"))
        self.label_10.setText(_translate("Dialog", "Исполнение ЦКС (ЦЦЦ)"))
        self.label_11.setText(_translate("Dialog", "Номер конфигурации:"))
        self.Freq_line.setText(_translate("Dialog", "00"))
        self.label_12.setText(_translate("Dialog", "Частота ЛФ (ЧЧЧ)"))
        self.label_13.setText(_translate("Dialog", ", кГц"))
        self.label_14.setText(_translate("Dialog", "УНЦА.465129.КК.НН.ДД.СС.ЗЗ - ЛЛ.(ЧЧЧ).ТТ.ЦЦЦ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
